import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const Dm_Sans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Web Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Dm_Sans.className}>
      <body>{children}</body>
    </html>
  );
}
