export const metadata = {
  title: "Experience",
  description: "Generated by create next app",
};

export default function Experience() {
  return (
    <div>
      <h1>Experience</h1>
    </div>
  );
}
